locustfile = locustfile.py
host = http://nginx
users = 100
spawn-rate = 10
run-time = 5m
web-port = 8089
web-host = 0.0.0.0
headless = false
csv = results/locust_results
html = results/report.html
loglevel = INFO
