[core]
host = http://nginx
users = 100
spawn_rate = 10
run_time = 5m
mode = standalone
web_port = 8089
bind_host = 0.0.0.0
headless = false

[reporting]
csv_prefix = results/locust_results
stats_history_enabled = true

[logging]
log_level = INFO
log_file = results/locust.log